name: mangas
description: "My mangas collection"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2
  path: ^1.8.3
  cached_network_image: ^3.3.1
  sqflite_common_ffi: ^2.3.2+1
  file_picker: ^6.1.1
  open_file: ^3.3.2
  permission_handler: ^11.3.0
  sqlite3_flutter_libs: ^0.5.20

flutter_launcher_icons:
  image_path: "assets/icon/icon.jpeg"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#a3a3a3"
  adaptive_icon_background: "#a3a3a3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true